# Generated by Django 6.0.3 on 2026-03-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='is_vectorized',
            field=models.BooleanField(default=False, verbose_name='Vetorizado?'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Processamento'),
        ),
    ]
