# Generated by Django 6.0.3 on 2026-03-11 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_knowledgebase_is_vectorized_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Nome da Conexão")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("postgres", "PostgreSQL"),
                            ("oracle", "Oracle"),
                            ("sap", "SAP"),
                            ("sqlserver", "SQL Server"),
                            ("sqlite", "SQLite"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Banco",
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255, verbose_name="Host")),
                ("port", models.PositiveIntegerField(blank=True, null=True, verbose_name="Porta")),
                ("database_name", models.CharField(blank=True, max_length=255, verbose_name="Nome do Banco")),
                ("username", models.CharField(blank=True, max_length=255, verbose_name="Usuário")),
                ("password", models.CharField(blank=True, max_length=255, verbose_name="Senha")),
                ("connection_params", models.JSONField(blank=True, default=dict, verbose_name="Parâmetros Extras")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
            },
        ),
    ]
