# Generated by Django 6.0.3 on 2026-03-11 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_datasource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'verbose_name': 'Fonte de Dado', 'verbose_name_plural': 'Fontes de Dados'},
        ),
        migrations.CreateModel(
            name='ChatAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Agente/Chat')),
                ('system_prompt', models.TextField(blank=True, help_text='Regras de como este agente deve se comportar.', verbose_name='Instruções de Comportamento (Prompt)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_sources', models.ManyToManyField(blank=True, related_name='agents', to='engine.datasource', verbose_name='Bancos de Dados Vinculados')),
                ('knowledge_bases', models.ManyToManyField(blank=True, related_name='agents', to='engine.knowledgebase', verbose_name='Bases de Conhecimento (RAG) Vinculadas')),
            ],
            options={
                'verbose_name': 'Agente de Chat',
                'verbose_name_plural': 'Agentes de Chat',
            },
        ),
    ]
